### ISSUE TITLE
dcc_projects - uma plataforma web para gerenciamento de projetos do DCC

### ISSUE THREAD

**Issue by matheushsouza** [aserg-ufmg/CursoEngenhariaSoftware#1]
**Equipe**
- Artur Marzano
- Ingrid Lagares
- João Victor Tamm
- Matheus de Souza

**Objetivo e descrição do sistema**
O grupo desenvolverá um prototipo de um sistema de gerenciamento de dados do DCC, que funcionaria como uma espécie de intranet do departamento, à qual todos os alunos e professores associados teriam acesso por meio do login do DCC. Esses dados podem ser de projetos, dados de funcionários, reserva de salas, eventos etc., porém na sprint do trabalho o grupo focará em dados de projetos.

O objetivo é que ao final da sprint tenha sido implementado um sistema em que seja possível criar e editar dados de usuários e adicionar restrições aos mesmos, além de adicionar, excluir e editar projetos, utilizando banco de dados. O sistema contará ainda com uma interface web básica para acesso a essas funcionalidades.

**Tecnologia**
Uma interface web, desenvolvida majoritariamente em Django com banco de dados MySQL.

**Comment by mtov** [comment]
OK, pessoal, proposta aprovada!

**Comment by matheushsouza** [comment]
**Repo:** https://github.com/matheushsouza/dcc_projects
