### ISSUE TITLE
Softwarrior

### ISSUE THREAD

**Issue by adlermferreira** [aserg-ufmg/CursoEngenhariaSoftware#10]
**Equipe:**

- Adler Melgaço Ferreira
- Hiago de Souza Cruz Alves e Silva
- Marcelo Luiz Harry Diniz Lemos
- Pedro Andrade Militão
- Pedro Elias Valadares Castanheira

O grupo desenvolverá um jogo 2D Platforming, no estilo dos jogos da franquia Mario.

**Features do jogo**
- 4 fases
- 4 tipos de inimigo
- 1 boss (um inimigo mais forte ao fim do jogo)
- Arte e Trilha sonora originais

Um sistema de upgrades também será feito, com o jogador recebendo um novo movimento no fim de cada fase(Exemplo: Pulo Duplo). O jogo conterá ainda um **Sistema de Save**, permitindo ao jogador salvar o seu progresso ao longo do jogo, para que não tenha que começar do início cada vez que fechá-lo. Além disso, haverá também um **Scoreboard Online**, para que os jogadores possam verificar e comparar a sua performance ao longo das fases.

**Tecnologia**

Usaremos a engine Godot e sua linguagem nativa, Gdscript, para a implementação da maioria dos recursos do jogo. O Scoreboard será feito através de um webservice com springboot em Java.

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by adlermferreira** [comment]
Repositório: https://github.com/Marcelo-Lemos/Softwarrior
