### ISSUE TITLE
Orbis: Biblioteca Virtual Para Crianças

### ISSUE THREAD

**Issue by fernandaars** [aserg-ufmg/CursoEngenhariaSoftware#11]
**Membros**
* Fernanda Aparecida R. Silva | 2016006433
* Italo L. Simas | 2016006611
* Ketlyn Caroline S. de Castro | 2016006654
* Scarlet G. Vianna | 2016006891

**Objetivo e Descrição**
O objetivo deste projeto é produzir uma plataforma online que estimule o hábito da leitura no público infantil. Para tanto, buscamos apresentar um acervo de livros digitais ilustrados e de ficção infanto-juvenil que, através de uma interface amigável e lúdica, podem ser selecionados de acordo com o gosto da criança.

**Tecnologias**
* HTML
* CSS
* Bootstrap
* PHP
* phpMyAdmin (MySQL)

**Comment by mtov** [comment]
Ok, proposta aprovada. Tema bastante interessante.

**Comment by fernandaars** [comment]
Link do Git: https://github.com/fernandaars/orbis
