### ISSUE TITLE
DoctOrg - Sistema de organização de uma clínica médica

### ISSUE THREAD

**Issue by guilhermedrud** [aserg-ufmg/CursoEngenhariaSoftware#12]
**Equipe:**
Guilherme Drummond | 2017014820
Guilherme Torres | 2015083744
Paula Jennifer |
Mariana Teatini |

**Objetivo de descrição do sistema:**
O grupo desenvolverá um sistema de gerenciamento de informações dos pacientes de uma clínica médica em que será possível acessar a ficha de cada paciente e obter o histórico de consultas do paciente. Também será possível organizar os horários das consultas em uma agenda.

**Tecnologia**

C# e MySQL

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by sabtorres** [comment]
https://github.com/torresguilherme/DoctOrg - link do repositorio

**Comment by johnatan-si** [comment]
O link do repositório está quebrado !


https://github.com/torresguilherme/DoctOrg

**Comment by sabtorres** [comment]
@johnatan-si eu consigo acessar ele sem problemas. voce recebe algum erro?
