### ISSUE TITLE
dccTalks - um webchat aberto para todos os membros do DCC

### ISSUE THREAD

**Issue by pardini01** [aserg-ufmg/CursoEngenhariaSoftware#13]
**Equipe:**
Diego Barros
Marcel Henrique
Pedro Thomas
Rafael Pardini

**Descrição:**
O objetivo do grupo é construir um chat para membros do DCC. A aplicação terá uma interface web, na qual qualquer pessoa com uma conta no DCC poderá fazer login de forma segura e utilizar o canal principal (aberto) para conversar sobre o que desejar, se informar sobre os mais recentes eventos do departamento ou sobre novas vagas de estágio. Além disso, será possível formar grupos privados, facilitando por exemplo a discussão de trabalhos práticos em grupo, o compartilhamento de materiais de estudo e, é claro, as conversas cotidianas com os colegas. O chat terá as funcionalidades de enviar e deletar mensagens de texto, enviar e deletar arquivos, criar e deletar canais privados, adicionar e deletar membros aos canais, editar o "apelido" do usuário, a foto de perfil e a biografia.

**Tecnologias:**
Backend - Node.js
Frontend - React
Dados dos usuários - banco SQL
Dados dos chats - a decidir

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by MarcelHMendes** [comment]
Repositório: https://github.com/MarcelHMendes/dccTalks.git
