### ISSUE TITLE
Quick Market - Aplicativo para compras de supermercado online e retirada in loco

### ISSUE THREAD

**Issue by FraFleury** [aserg-ufmg/CursoEngenhariaSoftware#14]
**Equipe:**

- Francisco Otávio Fleury Teixeira Pinto

- Ana Gontijo

- Felipe Eduardo dos Santos

O grupo se propõe a desenvolver um aplicativo/site para fazer pedidos num supermercado e retirá-los no local, pulando a parte mais chata e demorada das compras. O app vai receber o pedido, alocá-lo no sistema e dar uma expectativa de tempo e uma senha de retirada ao cliente.

**Tecnologias**

- Django

- Python 3

**Repositório do Projeto**

https://github.com/anagontijo/mercado_online

**Planilha de Horas e Tarefas**

https://docs.google.com/spreadsheets/d/1GhHlbCpD1l-TNLMpVlfTeii4q7icI9o0v-HNH9MK63g/edit?usp=sharing

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by mtov** [comment]
Só para lembrar de mandar o link do repositório (para a inspeção intermediária #1).

**Comment by johnatan-si** [comment]
O projeto não possui  a **Planilha de Apuração de Horas Trabalhadas (com tarefas e commits)**
