### ISSUE TITLE
StoryTeller - Sistema de auxilio a desenvolvimento de Softwares

### ISSUE THREAD

**Issue by TiagoNO** [aserg-ufmg/CursoEngenhariaSoftware#15]
# Equipe
        Henrique Urban
        Semar Martins
        Thiago Mohallen
        Tiago Negrisoli

# Descrição 

        O grupo propõe construir um sistema que auxilia o desenvolvimento e a estruturação de projetos de softwares. Ele tera como objetivo, facilitar a organização e aplicação de métodos de desenvolvimento, de forma que os usuários poderão definir os sprints, historias, tarefas, tudo em um ambiente de fácil visualização e modelagem. Dessa forma, o grupo almeja aperfeiçoar as técnicas de desenvolvimento de software ao mesmo tempo em que estuda a disciplina.

# Linguagem 

        Python

**Comment by mtov** [comment]
OK, proposta aprovada (só um detalhe: o campo descrição acima ficou em uma única linha; talvez seja um problema na tag markdown usada pelo mesmo).

**Comment by thiagommohallem** [comment]
https://github.com/semaraugusto/EngSoftTrello
