### ISSUE TITLE
UfmgLeaks - Plataforma de compartilhamento de material escolar com outros alunos da universidade

### ISSUE THREAD

**Issue by brenopoggiali** [aserg-ufmg/CursoEngenhariaSoftware#16]
Equipe: 
* Breno Poggiali de Sousa
* Gabriel de Person Pereira de Melo
* Gabriela Peres Neme
* João Henrique Costa
* Pedro Nascimento Costa

Sobre o sistema:
O objetivo do nosso sistema é desenvolver uma plataforma voltada para alunos da UFMG em que eles próprios podem alimentar o sistema e tirar proveito dele. Nossa ideia principal é que ele contenha algumas coisas:
* Login/cadastro com autenticação pelo email da UFMG
* Forma simples de upload de materiais (podem ser provas, apostilas, livros, listas de exercicio, etc)
* Forma simples de consultar, por matéria, todos os materiais disponíveis para aquela disciplina.

O nosso MVP (Minimum Viable Product) inclui principalmente essas 3 entregas acima. Caso tenhamos mais tempo disponível, pensamos em adicionar algumas features a mais:
* Ups e Downs para cada material
* Botão de report para cada material
* Lista de usuários com mais Ups dentro da plataforma

Tecnologia a ser usada:
* Backend: Flask (Microframework em Python)
* Frontend: HTML + CSS + JS
* Banco de dados: PostgreSQL

**Comment by mtov** [comment]
Ok, proposta aprovada. A ideia é interessante e tomara que dê certo e vire um "produto".

**Comment by brenopoggiali** [comment]
Link do repositório: https://github.com/brenopoggiali/UfmgLeaks
Link da planilha com os commits e Burndown chart: https://docs.google.com/spreadsheets/d/1m_xMYajkkzRHYYktt6b5GvDiEAU5XsoS23BfwdDMKgs/edit#gid=0
