### ISSUE TITLE
Vertra - Marketplace imobiliário com recomendação através de perfil social do usuário

### ISSUE THREAD

**Issue by 7oRR3s97** [aserg-ufmg/CursoEngenhariaSoftware#17]
**Membros**
Gabriel Torres Moreira
Alexandre Henrique Garcia de Paiva
Lucas Pedro da Silva Machado
Jonatas Cavalcante

**Objetivos e Descrição**
O sistema é uma plataforma MVP de uma startup existente. O sistema se baseia em um marketplace imobiliário focado na transparência, segurança e agilidade, trazendo para isso um sistema de informações georeferenciaveis de relevância e um sistema de recomendação baseado no perfil social dos usuários da plataforma.
Nesse sprint focaremos no desenvolvimento do sistema de recomendação que utilizará dados obtidos através de login do facebook e navegação no próprio site, cruzando-os com interesses de perfis semelhantes na plataforma.

**Tecnologias**
FrontEnd: angular 8
BackEnd: .NET core
Banco de dados: MongoDb (possibilidade de estudo para bd paralelo do sistema de recomendação em elasticSearch)

**Comment by mtov** [comment]
Ok, proposta aprovada (vejam que é importante dividir bem o trabalho entre os 4 membros do time).

**Comment by johnatan-si** [comment]
Só para lembrar de mandar o link do repositório (para a inspeção intermediária #1).
