### ISSUE TITLE
MovieRec - Sistema de catálogo e recomendação de filmes baseado em análises e preferências de usuários

### ISSUE THREAD

**Issue by felipelrib** [aserg-ufmg/CursoEngenhariaSoftware#18]
## Equipe:
- Alan Prado Araújo
- Felipe dos Santos Leão Ribeiro
- Francisco de Paula Dias Neto
- Igor Henrique Firmo e Santos
- Lorena Mendes Peixoto
- Marcos Carvalho de Assis

## Descrição do projeto:
Um sistema que armazena e exibe listagens de diversos filmes para o usuário. Este sistema utiliza de informações como preferências de gênero de filme, filmes já assistidos e avaliados, avaliações de outros usuários e atividades de outras pessoas seguidas pelo usuário atual para exibir recomendações de filmes que ele possa assistir.

## Tecnologias:
- Front-end com HTML, CSS, JavaScript e React
- Back-end com NodeJS e Express
- Banco de dados não-relacional com MongoDB
- Sistema de recomendação com Python e scikit-learn

## Link do repositório:
https://github.com/MovieRecEngSoft/MovieRec

**Comment by mtov** [comment]
OK, projeto aprovado.
