### ISSUE TITLE
NoPaper - cadernos virtuais colaborativos

### ISSUE THREAD

**Issue by vrjuliao** [aserg-ufmg/CursoEngenhariaSoftware#19]
Membros:
Gustavo Lelis Vergara
Lucas Starling de Paula Salles
Luiz Felipe Couto Gontijo
Matheus Tiago Pimenta de Souza
Vinicius Julião Ramos

NoPaper consiste na criação de cadernos de anotações, em que cada usuário, será autenticado e compartilhará suas anotações com seus seguidores. Os seguidores podem fazer cópias das anotações para editarem e adicionarem comentários nas anotações. As anotações serão executadas em markdown e assim.

Por se tratar de uma aplicação web, usaremos JavaScript (ReactJS) e Python (DJango) para a elaboração do frontend e backent respectivamente. Além disso, utilizaremos MySQL para o banco de dados do serviço.

link do repositório:
https://github.com/vrjuliao/nopaper

**Comment by mtov** [comment]
OK, projeto aprovado.

**Comment by vrjuliao** [comment]
A equipe decidiu fazer uma pequena alteração no projeto.
O backend também será desenvolvido em JavaScript usando NodeJS e utilizaremos um banco de dados não relacional para esse projeto, ao invés do MySQL.

**Comment by mtov** [comment]
OK, Vinicius, alteração aprovada!
