### ISSUE TITLE
Controle de acesso para instalações de uso restrito.

### ISSUE THREAD

**Issue by GGuedesAB** [aserg-ufmg/CursoEngenhariaSoftware#2]
**Equipe**
    - Gustavo Guedes
    - Victor Barbosa
    - Leone Max
    - (_Vazio_)

**Descrição do sistema**
A necessidade de se controlar o acesso a instalações exige um banco de informações para reconhecer usuários e definir permissões, dessa forma, este trabalho irá consistir em um sistema automatizado para realizar o controle de acesso de pessoas à uma determinada instalação. Para isso, o sistema possuirá uma seção de cadastro de novos acessos com dois diferentes níveis de permissão, administrador e usuário, tal que os administradores são aqueles que podem adicionar novos acessos. Além disso, dada a relevância da instalação que possuirá o sistema, os dados dos administradores e dos usuários serão criptografados a fim de fornecer uma segurança contra tentativas de invasão.

**Tecnologia**
Será utilizado um algorítimo de encriptação de dados, um banco de dados MySQL e uma interface gráfica para registro de novos acessos. A identificação do usuário será feita a partir do reconhecimento do código MAC de seu aparelho de telefonia móvel pessoal na rede do sistema.

**Comment by GGuedesAB** [comment]
> **Equipe**
> - Gustavo Guedes
> - Victor Barbosa
> - Leone Max
> - (_Vazio_)
> 
> **##Descrição do sistema**
> A necessidade de se controlar o acesso a instalações exige um banco de informações para reconhecer usuários e definir permissões, dessa forma, este trabalho irá consistir em um sistema automatizado para realizar o controle de acesso de pessoas à uma determinada instalação. Para isso, o sistema possuirá uma seção de cadastro de novos acessos com dois diferentes níveis de permissão, administrador e usuário, tal que os administradores são aqueles que podem adicionar novos acessos. Além disso, dada a relevância da instalação que possuirá o sistema, os dados dos administradores e dos usuários serão criptografados a fim de fornecer uma segurança contra tentativas de invasão ao sistema.
> 
> **##Tecnologia**
> Será utilizado um algorítimo de encriptação de dados, um banco de dados MySQL e uma interface gráfica para registro de novos acessos. A identificação do usuário será feita a partir do reconhecimento do código MAC de seu aparelho de telefonia móvel pessoal na rede do sistema.

**Comment by mtov** [comment]
OK, proposta de trabalho aprovada (sugestão: definir uma interface simples, intuitiva, fácil de usar etc).

E apenas duas dúvidas: (1) qual linguagem de programação? (2) qual framework/biblioteca para implementar gráfica?

**Comment by GGuedesAB** [comment]
Escolhemos as linguagens C/C++, para implementar a interface gráfica utilizando o GTK, e Python.

**Comment by GGuedesAB** [comment]
Repositório criado em: https://github.com/GGuedesAB/Access-Control-System
