### ISSUE TITLE
OuvICEx - Sistema de ouvidoria para denúncias, reclamações e sugestões aberto aos alunos do ICEx

### ISSUE THREAD

**Issue by isadorasalles** [aserg-ufmg/CursoEngenhariaSoftware#20]
**Equipe:**

Ana Flávia de Miranda Silva
Giovanna Louzi Bellonia
Igor Marques de Araujo
Isadora Alves de Salles
Thiago Martin Poppe

**Descrição do Projeto:**

OuvICEx consiste na criação de um sistema web para ouvidoria que armazena as denúncias, reclamações e sugestões de melhorias dadas pelos alunos do ICEx. O sistema deve ser fácil de usar para ser mais acessível. Além disso, será permitido que as denúncias sejam feitas de forma anônima ou não. Os usuários também podem optar por requisitar uma análise dos dados que já constam no nosso banco. As denúncias deverão se enquadrar em temas que resumem o contexto do argumento, como por exemplo machismo ou racismo. Bem como pode ser identificado o departamento ao qual a denúncia se refere, com isso é possível gerar estatísticas para os usuários, como por exemplo, quantas denúncias sobre machismo temos no departamento de ciência da computação. 

**Tecnologias:**

Front-end: HTML, CSS, Javascript, Bootstrap
Back-end: Flask (Framework em Python)
Sistema de gerenciamento de banco de dados: MySQL
Análise de dados: Python (uso de bibliotecas como Pandas, Matplotlib e Scikit-learn)

**Link do repositório:**
https://github.com/gilouzi/ouvIcex

**Comment by mtov** [comment]
OK, projeto aprovado.
