### ISSUE TITLE
Donit: um sistema para listas e lembretes

### ISSUE THREAD

**Issue by gabriel-cangucu** [aserg-ufmg/CursoEngenhariaSoftware#21]
## Membros
Gabriel Lima Canguçu
Isabela Marina Ferreira Pires
Gabriela Pereira Faria Paixão
Rafael Gonçalves de Oliveira
Vitor Henrique da Costa Gomes

## Descrição
O sistema apresentará um ambiente gerenciável de uma "to-do list" trazendo variações de funcionalidade para abranger diferentes tipos de listas, como agendas e lembretes para lista de tarefas do trabalho/faculdade, registro personalizado para exercícios/circuitos de academia e controle de gastos para lista de supermercado.

## Tecnologias
HTML
CSS
JavaScript
MySQL
Vue JS
Nodejs
API Rest

## Link para o repositório
https://github.com/gabriel-cangucu/Donit

**Comment by mtov** [comment]
OK, projeto aprovado.
