### ISSUE TITLE
Paddle, um sistema administrativo da federação mineira de tênis de mesa

### ISSUE THREAD

**Issue by lucaspellegrinelli** [aserg-ufmg/CursoEngenhariaSoftware#22]
### Equipe:
- Bárbara Gomes Ribeiro
- Bruno Peres Andreotti
- Isadora Cristina Rodrigues
- Lucas Pellegrinelli Machado
- Luiz Guilherme Leroy Vieira

### Principais funcionalidades
- Cadastro dos membros e frequentadores da Federação Mineira de Tênis de Mesa
- Publicação de notícias
- Organização de torneios internos e sistemas de ranking

### Tecnologia utilizada
- **Frontend:** [Vue.js](https://vuejs.org/)
- **Backend:** [Python](https://www.python.org/)
- **Banco de Dados:** [MySQL](https://mariadb.org/)

### Link para o repositório
https://github.com/lucaspellegrinelli/paddle

**Comment by mtov** [comment]
OK, projeto aprovado.
