### ISSUE TITLE
DCCommerce: Um Sistema Para Compra e Venda de Produtos

### ISSUE THREAD

**Issue by VictorHSMoura** [aserg-ufmg/CursoEngenhariaSoftware#23]
## Membros:
- Davi Braga Tolentino Veloso
- Júlia Fonseca de Sena
- Lucas Paulo Martins Mariz
- Thales Aparecido Silva Elias
- Victor Hugo Silva Moura

## Descrição:
O sistema DCCommerce consiste em uma plataforma web para compra e venda de produtos, permitindo que o usuário possa ser tanto um comprador quanto um vendedor na plataforma. Enquanto comprador, o usuário pode, além de fazer compras, avaliar o produto comprado por meio de comentários e de um sistema de pontuação, e o vendedor pelo mesmo sistema de pontuação. Já enquanto vendedor, o usuário pode cadastrar produtos para venda e, conferir suas avaliações pessoais e de seus produtos. Além disso, o sistema deverá possuir uma barra de pesquisa de produtos, bem como um mecanismo de filtragem dos mesmos, por categorias.

## Tecnologias:
- **Front-end**: Angular
- **Back-end**: NodeJS
- **Banco de Dados**: MySQL
- **Ferramenta de Testes**: Jest

## Repositório:
Repositório do trabalho disponível em https://github.com/VictorHSMoura/DCCommerce

**Comment by mtov** [comment]
OK, projeto aprovado.
