### ISSUE TITLE
Quanté?: Sistema de catalogação de preços de produtos e serviços

### ISSUE THREAD

**Issue by lorenaleao** [aserg-ufmg/CursoEngenhariaSoftware#24]
**Nome dos Integrantes da Equipe:**

- Guilherme Miranda
- Lorena Leão
- Matheus Guilherme Veloso
- Raphael Augusto
- Tomaz Gomes

**Descrição:**

Quanté? é um aplicativo mobile que permite aos usuários pesquisar preços de produtos e serviços. A vantagem que o usuário terá ao usar o aplicativo será a facilidade de comparar preços de diversos lugares em um único ambiente e encontrar a melhor opção de compra para ele. Para alimentar o app será feito algo semelhante ao que já é usado no waze, os próprios usuários alimentarão o sistema. Outra funcionalidade possível é saber, além do menor preço, qual o local mais próximo do usuário com o menor preço. 

**Tecnologia:** 
- API em Python
- Banco de dados: MongoDB
- Interface do app: React, Node.js

**Link para o repositório de desenvolvimento [aqui](https://github.com/lorenaleao/quante).**

**Comment by mtov** [comment]
OK, projeto aprovado.
