### ISSUE TITLE
Aircnc - Sistema de aluguel de casas/quartos

### ISSUE THREAD

**Issue by LucasMouraoFerreira** [aserg-ufmg/CursoEngenhariaSoftware#25]
### **Grupo:**
- Lucas Mourão Ferreira
- Ramon Ribeiro Feliciano
- Vitor Lucio dos Santos Ferreira
- Bruna Campos de Melo

### **Descrição:**
Com o sistema será possível criar uma conta, postar casas/quartos para alugar, alugar, pesquisar por lugares.. etc; 

### **Tecnologias Utilizadas:**
Backend do sistema será uma Rest Api escrita em Python no framework Flask e utilizando MySQL. O Frontend será feito com Javascript/CSS/HTML com React.

### **Repositório:**  
https://github.com/LucasMouraoFerreira/Aircnc

**Comment by mtov** [comment]
OK, projeto aprovado.
