### ISSUE TITLE
Skoolit: Um sistema para um novo modelo de escola

### ISSUE THREAD

**Issue by caioguedesam** [aserg-ufmg/CursoEngenhariaSoftware#26]
**Membros:**

- Arthur Souto Lima
- Caio Guedes de Azevedo Mota
- Gabriel Victor Carvalho Rocha
- Guilherme Bezerra dos Santos
- Lucas Mariani Paiva Caldeira Brant
- Luiz Felipe Mascarenhas Dalle Nery

**Descrição:** Skoolit será um sistema de gerenciamento escolar direcionado para alunos de idade de  ensino fundamental e médio, onde haverão cadastros de aluno e professor. Nesse sistema, alunos serão livres para montar sua grade e escolher as matérias que quiserem se matricular em um dado semestre (com algumas limitações básicas). As aulas e materiais serão disponibilizadas online pelo professor que ministra a matéria, que também poderá elaborar e postar questionários. Adicionalmente, matérias similares poderão ser recomendadas aos alunos baseados nas matérias que já se matricularam.

**Tecnologia:** Será implementado um sistema web, usando HTML/CSS (com uso de Bootstrap) e JavaScript para o front-end, Python (com a framework Flask) para o back-end e SQLite para gerenciamento de banco de dados em SQL.

**Link repositório:** [skoolit_engsoft](https://github.com/caioguedesam/skoolit_engsoft)

**Comment by mtov** [comment]
OK, projeto aprovado.
