### ISSUE TITLE
Servi: Sistema de contratação de serviços

### ISSUE THREAD

**Issue by felipecadar** [aserg-ufmg/CursoEngenhariaSoftware#27]
## Membros
- Bruno Varella Peixoto
- Felipe Cadar
- João Couto
- Keller Clayderman
- Marco Tulio Motta

## Descrição
Servi é uma plataforma web para a contratação e oferecimento de serviços. Por ele, clientes podem buscar pelo serviço que necessitam de uma gama de anunciantes da plataforma e acompanhar as etapas do processo até a conclusão, enquanto os comerciantes podem anunciar serviços que desejam prestar e assim combinar a contratação.
A ferramenta contará com uma interface intuitiva e sofisticada que visa proporcionar uma facilidade na navegação para ambos os lados da operação. A ideia principal é que o cliente possa solicitar serviços de maneira rápida e prática enquanto profissionais ganham mais um meio de comunicação para explorar o mercado e potencialmente encontrar novos clientes.

## Tecnologias
- Frontend: Vue.js / JavaScript
- Backend: Python + Flask
- DB: MongoDB

## Repositório
[https://github.com/felipecadar/Servi](https://github.com/felipecadar/Servi)

**Comment by mtov** [comment]
OK, projeto aprovado.
