### ISSUE TITLE
Penoso ou Mamãozinho: fórum de discussão de disciplinas

### ISSUE THREAD

**Issue by Henrique-Brito** [aserg-ufmg/CursoEngenhariaSoftware#28]
PoM: Penoso ou Mamãozinho

É um fórum para os alunos se informarem e compartilharem informações sobre as disciplinas ofertadas pelo departamento. Cada disciplina possui uma página dedicada em que os alunos podem fazer comentários sobre a matéria, achar informações sobre o professor alocado a ela e compartilhar links de materiais úteis. Além disso, os comentários serão ordenados por um sistema de 'likes' e 'dislikes', dessa forma, os alunos podem achar os comentários mais relevantes de forma mais eficiente.

Tecnologia:

Frontend: vue.js
Banco de Dados: MySQL
Backend: Python (Flask)

Integrantes:

Henrique Junqueira de Brito
Wesley Paulino Fernandes Maciel
Felipe Seppe de Faria
Vitor Franco Rezende

Repositório:

https://github.com/Henrique-Brito/Penoso-ou-Mamaozinho

**Comment by mtov** [comment]
OK, pessoal, projeto aprovado.
