### ISSUE TITLE
#Cancelado-Mudamos de tema - Luvy: App de namoro/encontro com filtros personalizados

### ISSUE THREAD

**Issue by gabrielsluz** [aserg-ufmg/CursoEngenhariaSoftware#29]
_Membros_

- Luiz Henrique de Melo Santos
- Elves Mateus Rodrigues
- Evandro Lucas Figueiredo Teixeira
- Otávio Augusto Silva
- Gabriel Santos Luz

_Descrição_

- Um aplicativo de namoros/encontros, semelhante ao Tinder, que permite que os usuários personalizem suas preferências com filtros e encontrem alguém de interesse com mais facilidade.

_Tecnologias_

- Front-end: **Kotlin**
- Back-end: **.NET Core (C#)**
- Database: **ElasticSearch**

_Repositório do projeto_

https://github.com/otavio-silva/EngenhariaDeSoftware_TP

**Comment by mtov** [comment]
OK, pessoal, projeto aprovado.
