### ISSUE TITLE
Sistema de gerenciamento de estoque e vendas

### ISSUE THREAD

**Issue by gabrielspires** [aserg-ufmg/CursoEngenhariaSoftware#3]
Objetivo e breve descrição do sistema:

O sistema em questão tem como objetivo:

- Cadastrar e correlacionar as mercadorias de uma loja em geral.

- Capacitar a venda e controle de estoque

- Gerenciar o cadastro de clientes e suas respectivas compras dentro do sistema

Tecnologia a ser utilizada:

- Aplicação mobile

- Cross-plataform em Flutter

- Google Firebase

**Comment by mtov** [comment]
Ok, proposta aprovada.

Uma dúvida apenas:

> [1] receber dados de espectros de silagem de milho

Como isso vai funcionar? Como os dados "chegarão" até o sistema?

**Comment by voidmarcus** [comment]
> Ok, proposta aprovada.
> 
> Uma dúvida apenas:
> 
> > [1] receber dados de espectros de silagem de milho
> 
> Como isso vai funcionar? Como os dados "chegarão" até o sistema?

.

**Comment by mtov** [comment]
Ok, com o escopo está bem definido (e não parece ser tão amplo), sugiro investir bastante na interface do sistema (facilidade de uso, usabilidade etc).

**Comment by gabrielspires** [comment]
Repositório criado:

https://github.com/raydangaspar/eng_soft_tp1
