### ISSUE TITLE
Teambuilder System

### ISSUE THREAD

**Issue by LuanFranco98** [aserg-ufmg/CursoEngenhariaSoftware#30]
Teambuilder System

Com Clashs cada vez mais frequentes no League of Legends e na ausência de um método para a formação de times no jogo ou na web tivemos a ideia de criar uma plataforma para que jogadores sem um time e times incompletos se encontrem e possam jogar o Clash.

As ideias iniciais e funcionalidades iniciais do projeto podem ser descritas a seguir:

Usuário:
-Nick no LOL
-Elo
-Função
-Função secundária
-Campeão principal
-Campeão secundário
-Campeão terciário
-Caixa para outras infos opcionais

Site:
-Perfil
-Busca por times
-Criar time

Busca:
-Preferencias por: Função principal, time quase fechado, elo próximo

Sistema de reputação do jogador
-De 1 a 5 no final da partida os jogadores avaliam os seus companheiros de time
-intuito de evitar "trolls"
-Sistema de honra igual ao LOL mesmo

Esse é apenas o esboço inicial e pode ser alterado conforme o projeto se desenrola.

Tecnologias:
Frontend: vue.js
Banco de Dados: MySQL
Backend: Python (Flask)

Integrantes:
Luan Franco
Mateus Figueiredo
Álvaro Rodrigues
Carlos Alberto de Carvalho Antonio

Repositório:
https://github.com/LuanFranco98/TP_EngSoft

**Comment by mtov** [comment]
OK, pessoal, projeto aprovado.
