### ISSUE TITLE
Omicron Messenger : Um aplicativo simples de envio de mensagens. 

### ISSUE THREAD

**Issue by EvandroLucas** [aserg-ufmg/CursoEngenhariaSoftware#31]
**Membros**

- Luiz Henrique de Melo Santos
- Elves Mateus Rodrigues
- Evandro Lucas Figueiredo Teixeira
- Otávio Augusto Silva
- Gabriel Santos Luz
- Descrição

Um aplicativo de envio e recebimento de mensagens, que salva as mensagens localmente. 
A ideia é começar com um sistema bem simples, oferecendo:
    - Capacidade de enviar e receber mensagens via uma interface gráfica
    - Persistência após fechar o aplicativo. 
Uma vez concluídos os passos anteriores, esperamos poder implementar: 
    - Grupos
    - Confirmação de envio e/ou leitura
    - Envio de imagens
    - Segurança , autenticação e criptografia

Front-end: Python ou Web (HTML,CSS,JS), ainda em discussão
Back-end: .NET Core (C#)
Database: SQLite
Repositório do projeto

https://github.com/otavio-silva/EngenhariaDeSoftware_TP

**Comment by mtov** [comment]
OK, aprovado!
