### ISSUE TITLE
QuickDash : uma dashboard de BI

### ISSUE THREAD

**Issue by LuanFranco98** [aserg-ufmg/CursoEngenhariaSoftware#32]
Membros da equipe:

•	Álvaro Rodrigues
•	Carlos Carvalho
•	Luan Franco
•	Mateus Figueiredo.

Descrição:

O QuickDash é uma solução BI rápida e intuitiva que agrega informações financeiras, comerciais e logísticas de um negócio. Ela tem o intuito de criar um panorama mais conciso e visual para auxiliar nas tomadas de decisões. Para isso, ocorre a importação dos dados de um ou mais BD’s. E assim, os mesmos são analisados produzindo informações, gráficos e tabelas. 
Na demonstração dos dados gerados, é utilizada uma plataforma web para facilitar a visualização das métricas e indicadores desejados pelo usuário final.

Tecnologias:

Frontend: Vue.js
Backend: Flask
Banco de dados: MySQL

Link do repositório de desenvolvimento:

https://github.com/LuanFranco98/TP_EngSoft

PS: Pela mudança no tempo para fazer o projeto resolvemos trocar do projeto "TeamBuilder" para esse novo

**Comment by mtov** [comment]
Ok, projeto aprovado.
