### ISSUE TITLE
HealthCare: Sistema para disponibilização das tabelas de preços para medicamentos e materiais aos prestadores de serviços de operadoras de planos de saúde.

### ISSUE THREAD

**Issue by PaulaViriato** [aserg-ufmg/CursoEngenhariaSoftware#33]
1. Integrantes

• Guilherme Pereira Lima
• Isabela Pastorini Felisberto
• Paula Jeniffer dos Santos Viriato

2. Descrição

O projeto foi inspirado em uma demanda da empresa Lemon 360 aos integrantes deste grupo, afim de suprir uma necessidade de operadoras de planos de saúde.

Toda operadora de planos de saúde disponibiliza aos seus prestadores de serviços tabelas de preços, tanto para medicamentos quanto para materiais hospitalares, porém tais tabelas são personalizadas para cada tipo de prestador, seja de acordo com os serviços prestados ou região do país onde o prestador se encontra. Tal disponibilização torna-se complicada e lenta,
além de demandar um trabalho extra para os funcionários.

Assim, o objetivo é que o sistema HealthCare auxilie nesta tarefa de disponibilização de tabelas de preços, tornando-a mais rápida e prática, tanto para as operadoras de planos de saúde quanto para os prestadores de serviços.

3. Funcionalidades

O sistema deve ter 3 módulos: Módulo Administrativo, Módulo para Operadoras e Módulo para Prestadores. As funcionalidades são delegadas à cada um destes módulos citados.

3.1. Módulo Administrativo

• Modificação de Senha
• Cadastro de Operadoras de Planos de Saúde
• Carregamento de Tabelas Originais de Preço (Governo)
• Associação entre Prestadores de Operadoras

3.2. Módulo para Operadoras

• Modificação de Senha
• Associação de Prestadores à Operadora
• Montagem de Tabelas de Preços
• Visualização de Tabelas de Preços
• Disponibilização de Tabelas aos Prestadores

3.3. Módulo para Prestadores

• Modificação de Senha
• Visualização de Tabelas de Preços
• Visualização de Tabelas Anteriores
• Acompanhamento da Modificação de Preços

4. Tecnologias

O sistema HealthCare irá tratar-se de uma plataforma web, sendo desenvolvida na linguagem PHP, com o auxílio de HTML e CSS. O banco de dados será desenvolvido na linguagem SQL, utilizando a ferramenta MySQL Workbench. Durante o desenvolvimento, o sistema será alocado localmente em um webservice Wamp.

O Padrão de Projeto de Software utilizado será o MVC-DAO, sendo que será delegado para cada um dos integrantes do grupo um dos pacotes que compõem o padrão.

5. Repositório

O repositório está disponibilizado no GitHub no seguinte endereço web:
[https://github.com/PaulaViriato/HealthCare](https://github.com/PaulaViriato/HealthCare)

**Comment by mtov** [comment]
OK, projeto aprovado (mas vejam que o prazo para definição do projeto era 07/08)
