### ISSUE TITLE
Project Passárgada - uma plataforma web para gerenciamento de livros de domínio público

### ISSUE THREAD

**Issue by anaciriaco** [aserg-ufmg/CursoEngenhariaSoftware#4]
**Equipe:**
Ana Flavia Ciríaco - 2018055008
Breno Matos - 2017086007
Francisco Galuppo Azevedo - 2017014960
Luiza Chagas Brandão Campos - 2017015010
Rennan Cordeiro - 2018054850 

**Objetivo e descrição do sistema:**
O sistema desenvolvido é baseado no Project Gutemberg e no site Domínio Público. Ele contará com livros que estão em domínio público, possibilitando sua leitura e download, e também terá usuários que poderão apreciar mais funcionalidades como lista de favoritos e recomendações de livros.

Ao término do sprint, almejamos haver implementado um sistema que permita consulta e download de livros, criação de contas para usuários que tenham funcionalidades como lista de favoritos e recomendação de novos livros. Para facilitar a utilização do sistema, será implementada uma interface gráfica básica.

**Tecnologia:**
Interface web, desenvolvida majoritariamente em Django com banco de dados MySQL.

**Comment by mtov** [comment]
Ok, proposta de sistema bastante interessante; aprovada.

**Comment by franciscogaluppo** [comment]
O repositório chama passargada:
https://github.com/brenomatos/passargada
