### ISSUE TITLE
Sistema de controle de finanças - Um sistema para gerenciamento de finanças em repúblicas ou apartamentos compartilhados.

### ISSUE THREAD

**Issue by TaynaraCruz** [aserg-ufmg/CursoEngenhariaSoftware#5]
Equipe: Taynara Lorraine Marcelino da Cruz, João Gabriel de Oliveira Bicalho, Larissa Gomes Malagoli, João Vitor Campos e José Oliveira.

Objetivo: Implementar um aplicativo ou um "webapp" para auxiliar pessoas que dividem apartamento ou moram em república na organização das finanças da casa e na divisão de despesas.

Tecnologia a ser usada: javascript, css, html, vue, nodejs, banco de dados (MySQL, PostgreSQL ou SQLite)

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by TaynaraCruz** [comment]
Link do repositório: https://github.com/TaynaraCruz/sistema-de-controle-de-financas
