### ISSUE TITLE
ComPet - Plataforma sobre adoção responsável de animais abandonados

### ISSUE THREAD

**Issue by orlandoenrico** [aserg-ufmg/CursoEngenhariaSoftware#6]
**Equipe**
Augusto Henrique Polizer
Enok Januário da Rocha
Fabio Lino Morato
Orlando Enrico Liz Silvério Silva

**Objetivo e descrição**
O projeto a ser elaborado busca facilitar a adoção e o suporte aos animais abandonados, bem como promover a conscientização sobre a adoção responsável dos mesmos.
O abandono de animais é um problema global. A negligência e o imobilismo social contribuem para a manutenção de um ciclo que traz prejuízos em diversos âmbitos. Além disso, a preferência pela compra de animais ao invés da adoção e a falta de informação tornam a situação ainda mais grave. Os custos de cuidados e tratamentos dos mesmos acabam dificultando a atuação de ONGs e voluntários que tem por objetivo acolher e ajudar os animais.
Pensando na dimensão do problema em questão, a solução teria como foco a promoção da atuação conjunta e sistemática da sociedade. Sendo assim, o portal desenvolvido teria, por objetivo, facilitar a adoção e o suporte aos animais abandonados.
Além de funcionar como um meio de [1] divulgação e [2] adoção de pets, o mesmo serviria como uma plataforma de [3] captação de recursos para ONGs que cuidam de animais. Portanto, mesmo que o usuário não possua condições de acolher um animal, poderia doar uma quantia para o cuidado dos pets. Por fim, o sistema ainda contaria com [4] informativos de denúncia sobre maus tratos, página de [5] divulgação de eventos (feiras de adoção, por exemplo) e uma espécie de [6] blog contendo textos sobre a adoção responsável visando promover a conscientização sobre o tema e desconstruir mitos que corroboram para a perpetuação do problema.

**Tecnologia usada**
Em um primeiro momento, ficou decidido que as seguintes ferramentas serão utilizadas para o desenvolvimento do sistema:
•	HTML 5
•	CSS 3
•	Bootstrap 4
•	PHP
•	Node.js
•	MySQL
Verificando necessidade antes do início da sprint, poderão ser realizadas alterações no conjunto de tecnologias a serem usadas.

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by orlandoenrico** [comment]
Link do repositório: [ComPet](https://github.com/orlandoenrico/ComPet)
