### ISSUE TITLE
MULTINDER - MULTINDER é o Único Lugar que Tem Interesse em Nutrir Dates Entre n Reprodutores

### ISSUE THREAD

**Issue by brunodemattos** [aserg-ufmg/CursoEngenhariaSoftware#7]
Equipe:

O sistema é um sistema de relacionamentos que permite que pessoas usem o sistema para se relacionar com outras pessoas.
Cada usuário irá preencher um formulário, de forma que o software possa juntar as pessoas mais próximas, de acordo com seus interesses.
Também vai existir a possibilidade de marcar encontros de conjuntos maiores de pessoas, como três pessoas. Afinal de contas, por que o amor deve se limitar a duas pessoas?
Usando procedimentos e métricas de distância no R^n nunca antes usadas em aplicativos de namoro, poderemos estimar com precisão incrível casais ideias. Além disso, como ninguém mais tem tempo para avaliar se quer ou não sair com alguém, o sistema só fornecerá uma única opção por pessoa, é pegar ou largar. 
Grande parte da inovação do sistema se deve ao fato de que ninguém nunca uniu conhecimento técnico de álgebra linear e conhecimento de banco de dados, web development e outros aspectos da computação.

**Comment by mtov** [comment]
Faltou especificar a tecnologia: linguagem, banco de dados, etc.

**Comment by brunodemattos** [comment]
A tecnologia usada envovelrá SQL para fazer o banco de dados, visto que todos os membros têm experiência com essa linguagem e podem realizar qualquer tarefa relacionada a essa parte do projeto. Nosso membro especialista em interfaces gráficas decidiu que o melhor jeito de construir esse importante componente do trabalho será feito em CSS. O time responsável pela parte matemática, ainda não decidiu ainda entre o software Mathematica, SageMath ou fazer uma biblioteca própria em C++ ou Python. Quaisquer funcionalidades adicionais podem ser feitas em Python, considerando que todos os participantes da equipe têm familiaridade com a linguagem que possui muitas bibliotecas extras que podem auxiliar e muito no desenvolvimento do software. Por último, a integração do projeto será feita usando programas escritos em C++, já que é uma linguagem em que é fácil de fazer diferentes programas "conversarem" por meio de chamadas do sistema e que a modularização é natural.

**Comment by mtov** [comment]
OK, aprovado.

**Comment by brunodemattos** [comment]
https://github.com/brunodemattos/MULTINDER
