### ISSUE TITLE
Divide A.I. - plataforma de acompanhamento e divisão de despesas.

### ISSUE THREAD

**Issue by GustavoA1604** [aserg-ufmg/CursoEngenhariaSoftware#8]
**Equipe:** 
Amanda Alkmim Rezende Teixeira | 2016026655
Gabriel Espeschit | 2015065541
Gustavo Emanuel Faria Araújo | 2017002482
Mateus Dantas Hora | 2015016249
Samuel Souza da Silva | 2016027511

**Objetivo e descrição do sistema:**
O grupo irá desenvolver um sistema capaz de disponibilizar um acompanhamento financeiro ao usuário. Tal software atuará em dois âmbitos: individualmente, auxiliando na organização de despesas próprias do usuário, permitindo a inserção de gastos divididos por categorias e com diferentes moedas; e em conjunto, possibilitando a divisão de despesas de um grupo, contendo as mesmas funcionalidades da utilização individual, porém com um sistema de simplificação de dívidas (A → B → C se torna A → C).

Além do controle de gastos, o sistema contará com uma aba de acompanhamento, contendo gráficos sobre as principais áreas de despesa, valor absoluto do grupo, e outras estatísticas julgadas relevantes. Assim, para o funcionamento completo, deve ser possível cadastrar usuários e grupos, assim como categorias e itens de compra.

**Tecnologia a ser usada:**
Para a conveniência e usabilidade do sistema, foi escolhido que o mesmo seria um aplicativo, disponível na plataforma Android e iOS. O desenvolvimento será realizado utilizando a framework Qt, responsável pela criação de interfaces gráficas em C++; também será utilizado JavaScript para o desenvolvimento dentro da framework. Por fim, será utilizado um banco de dados MySQL.

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by ssdasilva** [comment]
Repositório: https://github.com/ssdasilva/Divide-A.I.---plataforma-de-acompanhamento-e-divis-o-de-despesas..git
