### ISSUE TITLE
Musiquality - Software de composição de músicas.

### ISSUE THREAD

**Issue by joaopaulolara** [aserg-ufmg/CursoEngenhariaSoftware#9]
**Membros**
Leandro Luiz Duarte Teixeira
Bernardo Ferreira Torres
Bernardo Figueiredo Cipriano
João Paulo Lara Pinto

**Objetivo e descrição**
O programa a ser desenvolvido é uma plataforma para desenvolvimento e 'prototipagem' de músicas, podendo o usuário selecionar, adicionar e editar sons de multiplos instrumentos e notas musicais ao longo de sua composição. A qualquer momento, é possível ouvir o resultado parcial da obra para averiguar possíveis necessidades de modificações, a gosto do compositor.

**Tecnologia a ser usada**
Java, banco de dados (como mysql)

**Comment by mtov** [comment]
Ok, proposta aprovada.

**Comment by bernardo-torres** [comment]
Link do Repositorio: https://github.com/torresbf/Musiquality
